### ISSUE TITLE
MySQL --no-defaults flag causes incorrect socket path

### ISSUE THREAD

**Issue by Muffinman** [wp-cli/db-command#155] opened 2019-11-27 13:49 UTC
## Bug Report

**Describe the current, buggy behavior**

On my macOS system, I have MySQL set up to listen at /usr/local/var/mysql/mysql.sock. I have this correctly configured in my php.ini and mysql server/client config files so that everything works as normal.

For some reason, the `wp db` command seems to have the `--no-defaults` flag so all mysql client settings are ignored. This causes all `wp db` commands to fail as it falls back to the old socket path at the time MySQL was compiled.

I'm wondering what the thought process was behind this flag? As far as I know the defaults can be easily overridden by specifying the flags, so I can't see what purpose this has. I found the commits where this was added, but no mention of why.

https://github.com/wp-cli/db-command/commit/4fb859972901bef44a03c491316fa721b65b624e
https://github.com/wp-cli/db-command/commit/0bcaa756c60e55dc04ff42e09461ad3540325952

**Describe how other contributors can replicate this bug**

- Create custom MySQL socket path and make sure it is available and listening
- Set this socket path in php.ini and mysql client config
- Try `wp db import` or `wp db export`

**Example**

```
 ~> mysql 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 91809
Server version: 10.4.9-MariaDB Homebrew

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
```

```
 ~> mysql --no-defaults
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

**Describe what you would expect as the correct outcome**

The `wp db` command should correctly pick up the default socket path from the PHP ini or default MySQL client settings.

**Let us know what environment you are running this on**

```
OS:	Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
Shell:	/usr/local/bin/fish
PHP binary:	/usr/local/bin/php
PHP version:	7.3.11
php.ini used:	/usr/local/etc/php/7.3/php.ini
WP-CLI root dir:	/Users/matt/.composer/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	/Users/matt/.composer/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Provide a possible solution**

Remove `--no-defaults` from mysql commands, or attempt to fetch socket path from PHP / MySQL.

**Comment by schlessera** [comment] 2020-01-09 06:31
@Muffinman This will be fixed in the next release via #157 through the addition of a `--defaults` flag which counters the default `--no-defaults` behavior. This behavior is still the default, though, for backwards compatibility reasons.

**Closed** 2020-01-09 06:31 UTC

**Comment by schlessera** [comment] 2021-08-03 06:34
@janw-me I assume this is a duplicate of https://github.com/wp-cli/db-command/issues/185. I started fixing it via https://github.com/wp-cli/db-command/pull/206 but was slowed down because I hit a bug in WP core (https://core.trac.wordpress.org/ticket/53830).

**Comment by janw-me** [comment] 2021-08-03 08:11
Ahh yes this is exactly the same.
