### ISSUE TITLE
Make it easier to pipe tables into `wp search-replace`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/db-command#58] opened 2017-11-09 19:54 UTC
Doing so currently requires:

```
wp search-replace "SEARCH" "REPLACE" $(wp db tables wp_${blog_id}_* --all-tables | paste -s -d ' ' -)
```

From https://poststatus.slack.com/archives/C0413TGQZ/p1510238991000109

It'd be nice if `wp db tables` output could be passed directly to `wp search-replace`.

**Comment by schlessera** [comment] 2017-11-11 08:21
There are two approaches to this:

A. Add an additional `--format` option that outputs the elements as a single line separated by spaces
B. Make `wp search-replace` understand the `--format=csv` output

I think B. shouldn't be too hard to do. That might however break when somebody actually has commas in their table names.

Option A. is probably the safer better, but is less convenient.

**Comment by austinginder** [comment] 2018-10-02 18:30
The slack message has been archived. From what I can tell, this works as intended. Maybe this was already resolved? I tested the following in both `bash` and `zsh` shells. I'm running WP-CLI version: 2.0.1.

`wp search-replace sample123 sample124 $(wp db tables "wp_woo*" --all-tables) --dry-run --debug` 

Which according to the debugger expands properly to 

`Debug (bootstrap): argv: /usr/local/bin/wp search-replace sample123 sample124 wp_woocommerce_api_keys wp_woocommerce_attribute_taxonomies wp_woocommerce_downloadable_product_permissions wp_woocommerce_log wp_woocommerce_order_itemmeta wp_woocommerce_order_items wp_woocommerce_payment_tokenmeta wp_woocommerce_payment_tokens wp_woocommerce_sessions wp_woocommerce_shipping_zone_locations wp_woocommerce_shipping_zone_methods wp_woocommerce_shipping_zones wp_woocommerce_tax_rate_locations wp_woocommerce_tax_rates wp_woocommerce_termmeta --dry-run --debug (0.055s)`

**Comment by schlessera** [comment] 2018-10-03 11:31
I suppose the initial problem might have been related to an `$IFS` setting that didn't include the space.

Thanks for verifying this, @austinginder, closing the issue for now.

**Closed by schlessera** 2018-10-03 11:31 UTC
Labels: command:db, command:db-tables
